### ISSUE TITLE
injection engine only loads from specific build

### ISSUE THREAD

**Issue by triptych** [caridy/yui3-gallery#12]
context fiddle:

This one works:

http://jsfiddle.net/triptych/xxBC4/

it has the specific build specified: gallery: 'gallery-2011.07.06-19-30'

however for just a general include without the gallery build set - it no longer loads...
http://jsfiddle.net/triptych/nGU4n/
error:
GET http://yui.yahooapis.com/combo?gallery-2010.12.16-18-24/build/gallery-injection-engine/gallery-injection-engine-min.js 400 (Bad Request)

**Comment by caridy** [comment]
Modules that were created and pushed after the official YUI built will not be available without specifying a "gallery" tag. Basically, on every YUI built, the latest tag from the gallery (at that moment) will be used as the default tag. That's the way the loader works, hence there is not way you can load injection engine in yui 3.3.0 without the gallery version specified manually. It will work in 3.4.0 because at the time to the final release a future gallery tag will include a version of injection and bootstrap.
